import { useState } from 'react'
import Head from 'next/head'
import { Container, Row, Col, Form, Button } from 'react-bootstrap'
import Navbar from "../components/navbar"
import Sidebar from "../components/sidebar"
import Primary from "../components/primary"

export default function Home() {

  const [businessName, setBusinessName] = useState("Intangible Media");
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />             
      </Head>
      <Container fluid>
        <Row className="bg-dark">
          <Col>
            <Navbar />
          </Col>
        </Row>
        <Row>
          <Sidebar businessName={businessName} setBusinessName={setBusinessName} />
          <Primary businessName={businessName} />
        </Row>
      </Container>
    </div>
  )
}
