import { useState } from "react";
import Head from "next/head";
import { Container, Row, Col, Form, Button } from "react-bootstrap";
import Navbar from "../components/navbar";
import Sidebar from "../components/sidebar";
import Primary from "../components/primary";

export default function Home() {
  const [isRetainer, setIsRetainer] = useState(false)
  const [businessName, setBusinessName] = useState("");
  const [businessAddress, setBusinessAddress] = useState("");
  const [selectedServices, setSelectedServices] = useState([]);
  const [selectedSubServices, setSelectedSubServices] = useState([])
  const [services, setServices] = useState([
    {
      name: "Website Development",
      subServices: [
        "Hosting",
        "Google Analytics Setup",
        "Monthly Mantainace",
        "Custom Child Theme",
        "Develop Webpages Based on Mockup Designs",
      ],
    },
    {
      name: "Graphic Design",
      subServices: [
        "Logo Design",
        "Brand Guide",
        "Website Mockups",
        "Website Prototypes",
        "1 Hour Website Consultation"
      ],
    },
    {
      name: "Photography",
      subServices: [
        "Headshots",
        "Interior Shots",
        "Exterior Shots"
      ],
    },
    {
      name: "Videography",
      subServices: [
        "30 Second Promotional Video",
        "5 Minute Video"
      ],
    },
  ]);

  return (
    <div>
      <Head>
        <title>Contract Genorator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid>
        <Row className="bg-dark">
          <Col>
            <Navbar />
          </Col>
        </Row>
        <Row>
          <Sidebar
            businessName={businessName}
            setBusinessName={setBusinessName}
            businessAddress={businessAddress}
            setBusinessAddress={setBusinessAddress}
            services={services}
            setServices={setServices}
            selectedServices={selectedServices}
            setSelectedServices={setSelectedServices}
            selectedSubServices={selectedSubServices}
            setSelectedSubServices={setSelectedSubServices}
            isRetainer={isRetainer}
            setIsRetainer={setIsRetainer}
          />
          <Primary
            businessName={businessName}
            businessAddress={businessAddress}
            selectedServices={selectedServices}
            selectedSubServices={selectedSubServices}
            isRetainer={isRetainer}
          />
        </Row>
      </Container>
    </div>
  );
}
