import { useState } from "react";
import Head from "next/head";
import { Container, Row, Col, Form, Button } from "react-bootstrap";
import Navbar from "../components/navbar";
import Sidebar from "../components/sidebar";
import Primary from "../components/primary";

export default function Home() {
  const [businessName, setBusinessName] = useState("");
  const [businessAddress, setBusinessAddress] = useState("");
  const [selectedServices, setSelectedServices] = useState([]);
  const [services, setServices] = useState([
    "Website Development",
    "Graphic Design",
    "Photography",
    "Videography",
  ]);

  return (
    <div>
      <Head>
        <title>Contract Genorator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid>
        <Row className="bg-dark">
          <Col>
            <Navbar />
          </Col>
        </Row>
        <Row>
          <Sidebar
            businessName={businessName}
            setBusinessName={setBusinessName}
            businessAddress={businessAddress}
            setBusinessAddress={setBusinessAddress}
            services={services}
            setServices={setServices}
            selectedServices={selectedServices}
            setSelectedServices={setSelectedServices}
          />
          <Primary
            businessName={businessName}
            businessAddress={businessAddress}
            selectedServices={selectedServices}
          />
        </Row>
      </Container>
    </div>
  );
}
